### ISSUE TITLE
Separate "call for papers" and "voting" periods

### ISSUE THREAD

**Issue by iurisilvio** [luanfonceca/speakerfight#54] opened 2015-06-01 17:04 UTC
I don't know the right way to do it, but ordering by creation date is too biased.

**Comment by jonatasoliveira** [comment] 2015-06-01 18:39
I think you're talking about the ordering of proposals.

If it's correct, I agree with you that is not the best field to sort, but I don't agree that will cause any issue with the vote itself. Maybe the issue is not about the ordering and more about the presentation of the proposals to do the voting.

What do you think?

**Comment by iurisilvio** [comment] 2015-06-01 20:54
I have some problems with the current voting system.

In some past Python Brasil, I remember I voted after the proposals were sent. You have two distinct phases, first you do the call for papers and after it you do the voting.

If I send a late proposal, I'll have less votes because I had less days to receive votes and my proposal will be at the end of the list, receiving less attention.

As I said, I don't know how exactly is the fix for this issue, but I want to start the discussion.

**Comment by victor-torres** [comment] 2015-06-02 12:14
Hi, @iurisilvio.

Did you mean we need distinct periods, such as 'Call for papers' and the 'Voting' itself?

The issue title is not that clear. Could you review it, please?

**Comment by iurisilvio** [comment] 2015-06-02 12:33
@victor-torres yes, this is my idea. I created the issue because the ordering, but after some thought, I don't think it is possible to fix it reordering the proposals.

First, we need all proposals registered. This is the "Call for papers" time. I agree it is interesting to show the proposals and give some fake voting controls for social purposes.

After that, we need a voting period, maybe only for conference participants (it can be an option to the event creator). It is not a popularity contest, it is about what people in the conference want to watch.

This is basically what I saw in an ancient Python Brasil (2009?). I have no idea what platform they used, but I liked the system.

**Comment by luanfonceca** [comment] 2015-06-02 16:11
Hi @iurisilvio, i am totally agree with you, and this work on Speakerfight, it is just the Event creators keep the voting process private (In the private mode, the users can just send proposals, without voting or people seeing anything) until some time, and then just make it public, they will have that distinct moments.

I understand that this "trick" is a fault of the Speakerfight ux, we need to explain this steps in the event creation interface.

Thanks for your feedback!

**Comment by iurisilvio** [comment] 2015-06-02 16:15
I never created an event, so I didn't knew it. Thanks for the
clarification.

**Comment by luanfonceca** [comment] 2015-06-02 16:28
It is just a hack, as I code it i know how it works haha

**Comment by victor-torres** [comment] 2015-06-02 21:34
Seems that what you're asking for is already implemented and the actual voting process for Python Brasil [11] is due to the event's organization choice. So, wontfix, right?

By the way, I think fake voting is the worse scenario we could have. Imagine that I 'fake voted' someone. I will not come back to the event and vote again. It's already hard to get endusers clicks, trying to do that twice? Won't happen.

**Closed** 2015-06-08 05:33 UTC
